package shadow

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/MadAppGang/dingo/pkg/config"
)

func TestFindWorkspaceRoot(t *testing.T) {
	// Use the actual dingo repo as test case
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}

	// Walk up to find the repo root
	root, err := FindWorkspaceRoot(cwd)
	if err != nil {
		t.Fatalf("FindWorkspaceRoot failed: %v", err)
	}

	// Should find a go.mod
	goModPath := filepath.Join(root, "go.mod")
	if _, err := os.Stat(goModPath); err != nil {
		t.Errorf("Expected go.mod at %s", goModPath)
	}

	// Should contain "github.com/MadAppGang/dingo"
	content, _ := os.ReadFile(goModPath)
	if !strings.Contains(string(content), "github.com/MadAppGang/dingo") {
		t.Error("Expected go.mod to contain github.com/MadAppGang/dingo")
	}
}

func TestNewBuilder(t *testing.T) {
	cfg := config.DefaultConfig()
	builder := NewBuilder("/tmp/test", "build", cfg)

	if builder.WorkspaceRoot != "/tmp/test" {
		t.Errorf("Expected WorkspaceRoot /tmp/test, got %s", builder.WorkspaceRoot)
	}

	if builder.ShadowDir != "/tmp/test/build" {
		t.Errorf("Expected ShadowDir /tmp/test/build, got %s", builder.ShadowDir)
	}
}

func TestIsGeneratedFile(t *testing.T) {
	// Create a temp directory
	tmpDir, err := os.MkdirTemp("", "shadow-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a file with generated marker
	generatedFile := filepath.Join(tmpDir, "generated.go")
	if err := os.WriteFile(generatedFile, []byte(`// Code generated by dingo. DO NOT EDIT.
package main
`), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a file without marker
	normalFile := filepath.Join(tmpDir, "normal.go")
	if err := os.WriteFile(normalFile, []byte(`package main

func main() {}
`), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a file with line directive
	lineDirectiveFile := filepath.Join(tmpDir, "linedir.go")
	if err := os.WriteFile(lineDirectiveFile, []byte(`//line foo.dingo:1:1
package main
`), 0644); err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name string
		path string
		want bool
	}{
		{"generated marker", generatedFile, true},
		{"normal file", normalFile, false},
		{"line directive", lineDirectiveFile, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isGeneratedFile(tt.path)
			if got != tt.want {
				t.Errorf("isGeneratedFile(%s) = %v, want %v", tt.path, got, tt.want)
			}
		})
	}
}
